apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-app
  template:
    metadata:
      labels:
        app: platform-app
    spec:
      containers:
      - name: platform-container
        image: YOUR_DOCKER_USERNAME/platform-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
